info.app.name: '@project.name@'
info.app.version: '@project.version@'

spring:
    rabbitmq:
        host: ${RABBIT_HOST:localhost}

management:
    endpoints:
        web:
            exposure:
                include: "*"
        health:
            show-details: always

stockexchange:
    stocks: ABP,GDP,ERR,ZTE,QNX,TRE,IOP
    quotePerSecond: ${QUOTE_PER_SECOND:1}
